--14
SELECT DISTINCT * 
FROM PRODUCTS P
INNER JOIN(SELECT PRODUCTID FROM [ORDER DETAILS] OD
	INNER JOIN ORDERS O
	ON OD.ORDERID= O.ORDERID
	WHERE DATEDIFF(YEAR,O.ORDERDATE,GETDATE()) <25) OD
ON P.PRODUCTID=OD.PRODUCTID

--15
SELECT TOP 5 C.POSTALCODE FROM CUSTOMERS C
INNER JOIN (SELECT O.CUSTOMERID,OD.PRODUCTID,OD.QUANTITY FROM ORDERS O
INNER JOIN [ORDER DETAILS] OD
ON O.ORDERID = OD.ORDERID)	I
ON C.CUSTOMERID= I.CUSTOMERID
WHERE POSTALCODE IS NOT NULL
GROUP BY C.POSTALCODE
ORDER BY SUM(QUANTITY) DESC

--16
SELECT TOP 5 SHIPPOSTALCODE, COUNT(*)[SOLD]
FROM ORDERS O
WHERE DATEDIFF(YEAR,O.ORDERDATE,GETDATE()) <25
GROUP BY SHIPPOSTALCODE
ORDER BY SHIPPOSTALCODE

--17

SELECT CITY, COUNT(*) [CUSTOMERS COUNT]
FROM CUSTOMERS C
GROUP BY CITY

--18
SELECT CITY, COUNT(*) [CUSTOMERS COUNT]
FROM CUSTOMERS C
GROUP BY CITY
HAVING COUNT(*)>2

--19
SELECT DISTINCT C.CONTACTNAME FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUSTOMERID= O.CUSTOMERID
WHERE ORDERDATE> '1/1/98'

--20
SELECT C.CONTACTNAME, MAX(ORDERDATE) [SORT DATE] 
FROM ORDERS O
INNER JOIN CUSTOMERS C
ON O.CUSTOMERID= C.CUSTOMERID
GROUP BY CONTACTNAME

--21
SELECT C.CONTACTNAME,CP.S FROM CUSTOMERS C
INNER JOIN (SELECT CUSTOMERID, SUM(QUANTITY) S 
FROM [ORDER DETAILS] OD
INNER JOIN ORDERS O
ON OD.ORDERID =O.ORDERID
GROUP BY CUSTOMERID) CP
ON C.CUSTOMERID=CP.CUSTOMERID

--22
SELECT C.CUSTOMERID,CP.TOTAL 
FROM CUSTOMERS C
INNER JOIN (SELECT CUSTOMERID, SUM(QUANTITY) TOTAL 
FROM [ORDER DETAILS] OD
INNER JOIN ORDERS O
ON OD.ORDERID =O.ORDERID
GROUP BY CUSTOMERID
HAVING SUM(QUANTITY) >100) CP
ON C.CUSTOMERID=CP.CUSTOMERID

--23
SELECT SU.COMPANYNAME [SUPPLIER COMPANY NAME], SH.COMPANYNAME [SHIPPING COMPANY NAME]
FROM SUPPLIERS SU
CROSS JOIN SHIPPERS SH

--24
SELECT O.ORDERDATE, P.PRODUCTNAME 
FROM ORDERS O
CROSS JOIN PRODUCTS P

--25
SELECT DISTINCT E1.FIRSTNAME, E2.FIRSTNAME
FROM EMPLOYEES E1
INNER JOIN EMPLOYEES E2
ON E1.TITLE=E2.TITLE
WHERE E1.EMPLOYEEID<>E2.EMPLOYEEID

--26
SELECT DISTINCT E1.LASTNAME,E1.FIRSTNAME 
FROM EMPLOYEES E1
INNER JOIN EMPLOYEES E2
ON E1.EMPLOYEEID = E2.REPORTSTO
GROUP BY E1.LASTNAME, E1.FIRSTNAME
HAVING COUNT(E1.EMPLOYEEID) > 2

--27

SELECT CITY, COMPANYNAME, CONTACTNAME
FROM CUSTOMERS
UNION SELECT CITY, COMPANYNAME, CONTACTNAME
FROM SUPPLIERS
ORDER BY CITY
