--14
SELECT DISTINCT * 
FROM PRODUCTS P
INNER JOIN(SELECT PRODUCTID FROM [ORDER DETAILS] OD
	INNER JOIN ORDERS O
	ON OD.ORDERID= O.ORDERID
	WHERE DATEDIFF(YEAR,O.ORDERDATE,GETDATE()) <25) OD
ON P.PRODUCTID=OD.PRODUCTID

--15
SELECT TOP 5 C.POSTALCODE FROM CUSTOMERS C
INNER JOIN (SELECT O.CUSTOMERID,OD.PRODUCTID,OD.QUANTITY FROM ORDERS O
INNER JOIN [ORDER DETAILS] OD
ON O.ORDERID = OD.ORDERID)	I
ON C.CUSTOMERID= I.CUSTOMERID
WHERE POSTALCODE IS NOT NULL
GROUP BY C.POSTALCODE
ORDER BY SUM(QUANTITY) DESC

--16
SELECT TOP 5 SHIPPOSTALCODE, COUNT(*)[Sold]
FROM ORDERS O
WHERE DATEDIFF(YEAR,O.ORDERDATE,GETDATE()) <25
GROUP BY SHIPPOSTALCODE
ORDER BY SHIPPOSTALCODE

--17
select city, count(*) [Customers count]
from customers c
group by City

--18
SELECT CITY, COUNT(*) [CUSTOMERS COUNT]
FROM CUSTOMERS C
GROUP BY CITY
HAVING COUNT(*)>2

--19